workflow:
  name: "hybrid_recon"
  description: "Optimized hybrid reconnaissance workflow"
  arguments:
    domain: ""
  modules:
    - name: "passive_recon_module"
      tasks:
        - subfinder:
            command: "subfinder -t 100 -all -silent -d {domain} 2> /dev/null"
        
        - assetfinder:
            command: "assetfinder --subs-only {domain} 2> /dev/null"
        
        - dsieve_passive:
            command: "cat {passive_recon_module:subfinder} {passive_recon_module:assetfinder} | sed 's/\\*\\.//g' | sort -u | dsieve 2> /dev/null || true | grep {domain}"
            requires:
              - "passive_recon_module:subfinder"
              - "passive_recon_module:assetfinder"

        - alterx_passive:
            command: "cat {passive_recon_module:dsieve_passive} | alterx -enrich -silent 2> /dev/null || true | grep {domain}"
            requires:
              - "passive_recon_module:dsieve_passive"

        - puredns_passive:
            command: "cat {passive_recon_module:alterx_passive} | puredns resolve -r ~/resolvers.txt -l 1000 2> /dev/null"
            requires:
              - "passive_recon_module:alterx_passive"

        - naabu_passive:
            command: "cat {passive_recon_module:puredns_passive} | naabu -silent -c 100 -rate 2000 -p '443,80,81,300,591,593,832,981,1010,1311,1099,2082,2095,2096,2480,3000,3128,3333,4243,4567,4711,4712,4993,5000,5104,5108,5280,5281,5601,5800,6543,7000,7001,7396,7474' || true"
            requires:
              - "passive_recon_module:puredns_passive"

        - httpx_passive:
            command: "cat {passive_recon_module:naabu_passive} | httpx -silent -t 200 | sort -u"
            requires:
              - "passive_recon_module:naabu_passive"

    - name: "active_recon_module"
      tasks:
        - puredns_bruteforce:
            command: "puredns bruteforce ~/best-dns-wordlist.txt {domain} -q -r ~/resolvers.txt"

        - dsieve_active:
            command: "cat {active_recon_module:puredns_bruteforce} | sed 's/\\*\\.//g' | sort -u | dsieve 2> /dev/null || true | grep {domain}"
            requires:
              - "active_recon_module:puredns_bruteforce"

        - alterx_active:
            command: "cat {active_recon_module:dsieve_active} | alterx -enrich -silent 2> /dev/null || true | grep {domain}"
            requires:
              - "active_recon_module:dsieve_active"

        - puredns_active:
            command: "cat {active_recon_module:alterx_active} | puredns resolve -r ~/resolvers.txt -l 1000 2> /dev/null"
            requires:
              - "active_recon_module:alterx_active"

        - naabu_active:
            command: "cat {active_recon_module:puredns_active} | naabu -silent -c 100 -rate 2000 -p '443,80,81,300,591,593,832,981,1010,1311,1099,2082,2095,2096,2480,3000,3128,3333,4243,4567,4711,4712,4993,5000,5104,5108,5280,5281,5601,5800,6543,7000,7001,7396,7474' || true"
            requires:
              - "active_recon_module:puredns_active"

        - httpx_active:
            command: "cat {active_recon_module:naabu_active} | httpx -silent -t 200 | sort -u"
            requires:
              - "active_recon_module:naabu_active"

    - name: "misc_module"
      tasks:
        - tlsx:
            command: "cat {passive_recon_module:httpx_passive} {active_recon_module:httpx_active} | sort -u | tlsx -san -cn -silent -resp-only -c 500 | sort -u"
            requires:
              - "passive_recon_module:httpx_passive"
              - "active_recon_module:httpx_active"

        - tlsx_filter:
            command: "cat {misc_module:tlsx} | grep -v {domain} || true"
            requires:
              - "misc_module:tlsx"

        - dnsx:
            command: "cat {passive_recon_module:puredns_passive} {active_recon_module:puredns_active} | sort -u | dnsx -silent -recon -resp"
            requires:
              - "passive_recon_module:puredns_passive"
              - "active_recon_module:puredns_active"

        - nuclei_passive:
            command: "cat {passive_recon_module:httpx_passive} | nuclei -c 100 -silent -es low,info"
            requires:
              - "passive_recon_module:httpx_passive"

        - nuclei_active:
            command: "cat {active_recon_module:httpx_active} | nuclei -c 100 -silent -es low,info"
            requires:
              - "active_recon_module:httpx_active"

        - httpx_merged:
            command: "cat {passive_recon_module:httpx_passive} {active_recon_module:httpx_active} | sort -u"
            requires:
              - "passive_recon_module:httpx_passive"
              - "active_recon_module:httpx_active"

        - nuclei_merged:
            command: "cat {misc_module:nuclei_passive} {misc_module:nuclei_active} | sort -u"
            requires:
              - "misc_module:nuclei_passive"
              - "misc_module:nuclei_active"