workflow:
  name: "hybrid_recon"
  description: "Combined active and passive reconnaissance workflow"
  args:
    - domain: ""
  modules:
    - name: "passive_recon_module"
      tasks:
        - passive_asset_discovery_v1:
            command: "subfinder -t 100 -all -silent -d {domain} 2> /dev/null"
        
        - passive_asset_discovery_v2:
            command: "assetfinder --subs-only {domain} 2> /dev/null"
        
        - passive_asset_enrichment:
            command: "cat {passive_recon_module:passive_asset_discovery_v1} {passive_recon_module:passive_asset_discovery_v2} | sed 's/\\*\\.//g' | sort -u | dsieve 2> /dev/null || true"
            requires:
              - "passive_recon_module:passive_asset_discovery_v1"
              - "passive_recon_module:passive_asset_discovery_v2"

    - name: "active_recon_module"
      tasks:
        - dns_bruteforcing:
            command: "puredns bruteforce ~/best-dns-wordlist.txt {domain} -q -r ~/resolvers.txt"

        - active_asset_enrichment:
            command: "cat {active_recon_module:dns_bruteforcing} | sed 's/\\*\\.//g' | sort -u | dsieve 2> /dev/null || true"
            requires:
              - "active_recon_module:dns_bruteforcing"

    - name: "combined_module"
      tasks:
        - combined_assets:
            command: "cat {passive_recon_module:passive_asset_enrichment} {active_recon_module:active_asset_enrichment} | sort -u"
            requires:
              - "passive_recon_module:passive_asset_enrichment"
              - "active_recon_module:active_asset_enrichment"
        
        - wordlist_generator:
            command: "cat {combined_module:combined_assets} | alterx -enrich -silent 2> /dev/null || true"
            requires:
              - "combined_module:combined_assets"

        - dns_resolving:
            command: "cat {combined_module:wordlist_generator} | puredns resolve -r ~/resolvers.txt -l 1000 2> /dev/null"
            requires:
              - "combined_module:wordlist_generator"

        - port_scanning:
            command: "cat {combined_module:dns_resolving} | naabu -silent -c 100 -rate 2000 -p '443,80,81,300,591,593,832,981,1010,1311,1099,2082,2095,2096,2480,3000,3128,3333,4243,4567,4711,4712,4993,5000,5104,5108,5280,5281,5601,5800,6543,7000,7001,7396,7474' || true"
            requires:
              - "combined_module:dns_resolving"

        - http_probing:
            command: "cat {combined_module:port_scanning} | httpx -silent -t 200 | sort -u"
            requires:
              - "combined_module:port_scanning"

    - name: "misc_module"
      tasks:
        - tls_grabber:
            command: "cat {combined_module:http_probing} | tlsx -san -cn -silent -resp-only -c 500 | sort -u"
            requires:
              - "combined_module:http_probing"

        - tls_filter:
            command: "cat {misc_module:tls_grabber} | grep -v {domain} || true"
            requires:
              - "misc_module:tls_grabber"

        - records_dump:
            command: "cat {combined_module:dns_resolving} | dnsx -silent -recon -resp"
            requires:
              - "combined_module:dns_resolving"

        - vulnerability_scanner:
            command: "cat {combined_module:http_probing} | nuclei -c 100 -silent -es low,info"
            requires:
              - "combined_module:http_probing"